# For the changes to take effect, run the command: qden reload db
[mysqld]
max_allowed_packet=1024M
innodb_log_buffer_size=256M
innodb_buffer_pool_size=4G
innodb_log_file_size=1G
innodb_write_io_threads=16
innodb_flush_log_at_trx_commit=0
innodb_strict_mode=OFF
